### ISSUE TITLE
Blocklist for email domains

### ISSUE THREAD

**Issue by psmiraglia** [saasform/saasform#115]
#### As a...

service administrator

#### I want to...

be able to enable end configure a blocklist to filter email domains that can be used to signup

#### So that...

fake signup attempts relying on temporary email services (e.g. 10minutemail.com) could be drastically reduced

**Comment by psmiraglia** [comment]
FYI, https://block-temporary-email.com

```
$ curl -s https://block-temporary-email.com/check/domain/kiabws.com | jq
{
  "status": 200,
  "temporary": true,
  "dns": true
}

$ curl -s https://block-temporary-email.com/check/domain/gmail.com | jq
{
  "status": 200,
  "temporary": false,
  "dns": true
}
```

**Comment by 0x0ece** [comment]
Is this maintained? I quickly searched, there are many similar services, but often time the lists are small or not maintained. This one seems to have a very big list, but I'm unsure if/how they keep it up to date.

I'm a bit concerned about introducing an external api call during signup. And maintaining a list seems a painful/never ending job.

Maybe we can add this feature later as an additional app? We could have different apps from diff providers. Thoughts?

**Comment by psmiraglia** [comment]
> Is this maintained? I quickly searched, there are many similar services, but often time the lists are small or not maintained. This one seems to have a very big list, but I'm unsure if/how they keep it up to date.

That service is just an example. It's the result of a rapid query on google. I think the list is populated by scraping well known temporary services.

> I'm a bit concerned about introducing an external api call during signup. And maintaining a list seems a painful/never ending job.
>
> Maybe we can add this feature later as an additional app? We could have different apps from diff providers. Thoughts?

Yep! The provider-specific app/plugin seems to me also a valid way. My original idea was to have this feature highly configurable by the end user. The configuration could include

- a switch to enable/disable the feature (e.g. `verify_mail_domain: bool`)
- a parameter to select between while/black list (e.g. `verify_mail_domain_approach: ['white', 'black']`)
- a parameter to specify the type of the list (e.g. `verify_mail_domain_source_type: ['file', 'remote', 'api', 'db']`)
    - `file`: `/path/to/file.txt`
    - `remote`: `https://www.example.com/file.txt`
    - `db`: `mongodb://mongodb0.example.com:27017`
    - `api`: `https://api.example.com/verify` (it could require additional parameters to specify the API key and, for instance, the query template)

**Comment by 0x0ece** [comment]
(replaced black/white -> block/allow)

**Comment by 0x0ece** [comment]
https://github.com/reacherhq/check-if-email-exists
