### ISSUE TITLE
"next" attribute not working as intended

### ISSUE THREAD

**Issue by vishnupsatish** [saasform/saasform#143]
#### Repro

1. Run demo-flask 
2. Go to http://localhost:5000/protected without logging in
3. Log in

#### Current behavior

It goes to the SaaS placeholder dashboard.

#### Expected behavior

It returns to http://localhost:5000/protected

#### Environment

macOS 11.2.3, Python 3.9.0, latest version of Docker Desktop for Mac

#### Additional details

N/A

**Comment by 0x0ece** [comment]
Good catch - the SaaS (demo-flask in this case) should add the `next` query param like /login?next=http://localhost:5000/protected

**Comment by vishnupsatish** [comment]
Yes, it does add the attribute, but when I log in, it doesn't redirect me to the query parameter's value.

**Comment by 0x0ece** [comment]
Oh ok - taking a look. Are you using the latest image right? Because we fixed some weird behavior recently (for example, if you switch from /login to /signup now it should preserve the param next).
```$ docker images | grep saasform
saasform/saasform                                           latest          ff60e2d722be   8 days ago     362MB```

**Comment by vishnupsatish** [comment]
Yes, I am using the latest image, I just installed it a few hours ago actually.

**Comment by 0x0ece** [comment]
You prob need to change this line to localhost:5000:
https://github.com/saasform/saasform/blob/main/data/config/saasform.yml#L1

**Comment by 0x0ece** [comment]
I just tested (with the change) and everything works for me.
1. Edited saasform.yml
2. Run docker-compose up + demo-flask (on port 5000)
3. Navigate to http://localhost:5000/protected
4. Got redirected to http://localhost:7000/login?next=http://localhost:5000/protected
5. Logged in, got redirected back to http://localhost:5000/protected

**Comment by vishnupsatish** [comment]
I will try doing so, thank you. Maybe I was using the wrong port.
