### ISSUE TITLE
Sending email from SendGrid issue

### ISSUE THREAD

**Issue by vishnupsatish** [saasform/saasform#149]
#### What needs to be done?
The scope of this task, in a couple of lines.

Make sure the email parameter in the website.yml file does not need to be changed in order to send the email.

#### Details that might help to better understand the problem
Some details about the task, if the problem is not obvious

I changed the SENDGRID_* parameters, but sending emails failed, and once I changed the email parameter in website.yml, it was able to send an email. This is confusing to users of SaaSform, as I was under the impression that changing items in the website.yml file only changed the website's content and look/feel, and did not change the email sending.

#### Brief summary of any previous discussion of this task
N/A

**Comment by 0x0ece** [comment]
Good point. I think it's better to just remove [SENDGRID_SEND_FROM](https://github.com/saasform/saasform/blob/main/data/config/saasform.yml#L34) as the email should be in website.yml independently (it's displayed in a bunch of places). @davidevernizzi opinions?

**Comment by vishnupsatish** [comment]
I believe that the SENDGRID_SEND_FROM should not be removed, and the email used to send from SendGrid should be independent from the email displayed, as many potential customers may have different "sending" emails and contact emails.
