### ISSUE TITLE
Create Docker autobuild to support arm64

### ISSUE THREAD

**Issue by 0x0ece** [saasform/saasform#95]
#### What needs to be done?

Create Docker autobuild to support arm64, i.e. Apple M1 (and maybe rpi?)

#### Details that might help to better understand the problem

Example: https://github.com/ckulka/docker-multi-arch-example

**Comment by psmiraglia** [comment]
Let's start working on it (https://github.com/psmiraglia/saasform/tree/wip/create-docker-autobuild-to-support-arm64).

I manually built (on `x86_64` machine) an `arm64v8` version of the `saasform/saasform` image.

```
# prepare the dev environment with the magic things
$ apt-get install qemu-user-static
$ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

# build the arm64v8 image
$ cd src/webapp
$ docker build --tag psmiraglia/saasform-arm64v8:0.0.8 -f Dockerfile.arm64v8 .

# push on Docker Hub
$ docker push psmiraglia/saasform-arm64v8:0.0.8
```
 Hey ARMers, could you make a try? Just to know if I'm on the right way...

```
$ docker pull psmiraglia/saasform-arm64v8
```

**Comment by 0x0ece** [comment]
It works. However, for some reason also the autobuild done by Docker Hub already works... I'm a bit confused, but maybe this task was useless!?

**Comment by psmiraglia** [comment]
I drafted a GH action ([`build_multi_arch.yml`](https://github.com/psmiraglia/saasform/blob/eea719d44a302b0136860a6c9b96a40888981aac/.github/workflows/build_multi_arch.yml)) to build a multi-arch image by relying on [Docker Buildx](https://docs.docker.com/buildx/working-with-buildx/). The action still contain some hard-coded values (e.g. image tags) but  the core should be ok. The resulting images are available on Docker Hub at [`psmiraglia/saasform`](https://hub.docker.com/r/psmiraglia/saasform/tags?page=1&ordering=last_updated). Could you ARMers try again?

```
$ docker pull psmiraglia/saasform:latest
$ docker run -ti --rm psmiraglia/saasform:latest uname -m
```
